const PRESETS = [
  {
    name: "クラシック",
    dotColor: "#000000",
    bgColor: "#ffffff",
    dotStyle: "square",
    cornerSquareStyle: "square",
    cornerDotStyle: "square",
    gradient: false,
  },
  {
    name: "ブルーラウンド",
    dotColor: "#1a73e8",
    bgColor: "#ffffff",
    dotStyle: "rounded",
    cornerSquareStyle: "extra-rounded",
    cornerDotStyle: "dot",
    gradient: false,
  },
  {
    name: "夜空",
    dotColor: "#7eb8da",
    bgColor: "#0d1117",
    dotStyle: "rounded",
    cornerSquareStyle: "extra-rounded",
    cornerDotStyle: "dot",
    gradient: false,
  },
  {
    name: "サンセット",
    dotColor: "#ff6b35",
    bgColor: "#fff8f0",
    dotStyle: "extra-rounded",
    cornerSquareStyle: "extra-rounded",
    cornerDotStyle: "dot",
    gradient: true,
    gradientColor1: "#ff6b35",
    gradientColor2: "#f7c948",
    gradientType: "linear",
    gradientAngle: 135,
  },
  {
    name: "フォレスト",
    dotColor: "#2d6a4f",
    bgColor: "#f0f7f4",
    dotStyle: "classy-rounded",
    cornerSquareStyle: "extra-rounded",
    cornerDotStyle: "dot",
    gradient: false,
  },
  {
    name: "モノクロドット",
    dotColor: "#333333",
    bgColor: "#ffffff",
    dotStyle: "dots",
    cornerSquareStyle: "dot",
    cornerDotStyle: "dot",
    gradient: false,
  },
  {
    name: "オーシャン",
    dotColor: "#006994",
    bgColor: "#e8f4f8",
    dotStyle: "rounded",
    cornerSquareStyle: "extra-rounded",
    cornerDotStyle: "dot",
    gradient: true,
    gradientColor1: "#006994",
    gradientColor2: "#00b4d8",
    gradientType: "linear",
    gradientAngle: 180,
  },
  {
    name: "ラベンダー",
    dotColor: "#7c3aed",
    bgColor: "#faf5ff",
    dotStyle: "extra-rounded",
    cornerSquareStyle: "extra-rounded",
    cornerDotStyle: "dot",
    gradient: true,
    gradientColor1: "#7c3aed",
    gradientColor2: "#c084fc",
    gradientType: "radial",
    gradientAngle: 0,
  },
];
